global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'myappointment-app'
    metrics_path: 'appointment/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'docker.for.mac.localhost:8000' ]
    #        TODO why this is not working?
    #      - targets: [ 'appointment-api:8000' ]
    basic_auth:
      username: "myapp"
      password: "myapp"
  - job_name: 'mail-app'
    metrics_path: 'mail/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'docker.for.mac.localhost:8001' ]
    #        TODO why this is not working?
    #      - targets: [ 'mail-api:8001' ]
    basic_auth:
      username: "myapp"
      password: "myapp"