server:
  port: 9000
  ssl:
    key-store: classpath:healthservice.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: healthservice
    key-password: password
spring:
  cloud:
    gateway:
      routes:
        - id: appointment_id
          uri: 'http://localhost:8000'
          predicates:
            - Path=/appointment/**
        - id: mail_id
          uri: 'http://mail-api:8001'
          predicates:
            - Path=/mail/**
  application:
    name: API-GATEWAY
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9001/eureka/
    healthcheck: true
  instance:
    hostname: api-gateway
