server:
  port: 9000
spring:
  cloud:
    gateway:
      routes:
        - id: appointment_id
          uri: 'http://appointment-api:8000'
          predicates:
            - Path=/appointment/**
        - id: mail_id
          uri: 'http://mail-api:8001'
          predicates:
            - Path=/mail/**
  application:
    name: API-GATEWAY
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-discovery:9001/eureka/
    healthcheck: true
  instance:
    hostname: api-gateway